#!/bin/bash

# Move this to /usr/local/bin/* as it can be very useful when you are testing this in other projects

PACKAGE="$1"
ROOT="/Users/theodor/Projects/bluelibs/packages"

rm -rf node_modules/\@bluelibs/$PACKAGE/dist
rm -rf node_modules/\@bluelibs/$PACKAGE/src

cp -r $ROOT/$PACKAGE/dist "./node_modules/@bluelibs/$PACKAGE/dist"
cp -r $ROOT/$PACKAGE/src "./node_modules/@bluelibs/$PACKAGE/src"
